import subprocess, os, re

UNPACK = r"C:\Users\Vincent\.workbuddy\plugins\marketplaces\cb_teams_marketplace\plugins\document-skills\skills\docx\scripts\office\unpack.py"
PY = r"C:\Users\Vincent\.workbuddy\binaries\python\envs\default\Scripts\python.exe"
OUT = "tpl_unpacked"

checks = {
    "HK_ROM_Template_Bank.docx": ["Date Entered", "Member Name", "Shareholding %", "Generated by", "Director's Signature", "Witness Signature", "Company Chop"],
    "BVI_ROM_Template_Audit.docx": ["Shares Acquired", "Shares Transferred", "Distinctive Nos.", "Registered Agent Confirmation", "BVI 2018", "Consideration Paid"],
    "HK_ROD_Template_Bank.docx": ["Date Appointed", "NRIC/Passport", "Companies Ordinance (Cap. 622)", "Director's Signature", "Witness Signature"],
    "BVI_ROD_Template.docx": ["ORIGINAL", "COPY", "For Individual Director", "For Corporate Director", "Registered Office or Principal Office", "BVI 2018"],
}

for fname, markers in checks.items():
    path = os.path.join("deliverables", fname)
    d = os.path.join(OUT, fname.replace(".docx", ""))
    subprocess.run([PY, UNPACK, path, d], capture_output=True)
    txt = ""
    for root, _, files in os.walk(d):
        for f in files:
            if f.endswith(".xml"):
                txt += open(os.path.join(root, f), encoding="utf-8", errors="ignore").read()
    print(f"\n=== {fname} ===")
    for m in markers:
        print(f"  {'OK ' if m in txt else 'MISS'} {m}")
    gc = len(re.findall(r"w:gridCol", txt))
    print(f"  gridCol count: {gc}")
