const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },
  description: String,
  type: {
    type: String,
    enum: ['filing', 'compliance', 'meeting_preparation', 'document_review', 'signing', 'other'],
    required: true
  },
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company'
  },
  meeting: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Meeting'
  },
  personnel: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Personnel'
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent'],
    default: 'medium'
  },
  status: {
    type: String,
    enum: ['pending', 'in_progress', 'completed', 'overdue'],
    default: 'pending'
  },
  dueDate: {
    type: Date,
    required: true
  },
  completedDate: Date,
  assignedTo: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],
  // v5.1 会议纪要闭环强化
  // autoGenerated: 由纪要关键词（签署/签字/盖章）自动识别生成的待办，区别于手工创建
  autoGenerated: { type: Boolean, default: false },
  // responsiblePerson: 负责人姓名（演示/无 User 账号时可直接写名字；关联 User 仍走 assignedTo）
  responsiblePerson: { type: String },
  // hasAttachment: 是否已有上传的签署/扫描附件——signing 类 Task 必须此为真方可标记完成
  hasAttachment: { type: Boolean, default: false },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  notes: [{
    content: String,
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    createdAt: {
      type: Date,
      default: Date.now
    }
  }],
  reminders: [{
    date: Date,
    sent: {
      type: Boolean,
      default: false
    }
  }]
}, {
  timestamps: true
});

// Update status based on due date
taskSchema.pre('save', function(next) {
  if (this.status === 'pending' && this.dueDate < new Date()) {
    this.status = 'overdue';
  }
  next();
});

// v5.0 读时聚合索引：以 company / personnel / meeting 引用为聚合键
taskSchema.index({ company: 1 });
taskSchema.index({ personnel: 1 });
taskSchema.index({ meeting: 1 });
taskSchema.index({ dueDate: 1 });
taskSchema.index({ status: 1 });
// Dashboard 统计（pending/overdue）/ 公司任务看板
taskSchema.index({ status: 1, dueDate: 1 });
taskSchema.index({ company: 1, status: 1 });
// 全文本搜索索引（搜索增强 M2.1）
taskSchema.index({ title: 'text', description: 'text' });

module.exports = mongoose.model('Task', taskSchema);
