/**
 * 29 条预设合规规则定义（v5.0：jurisdiction 统一为英文 HK/BVI/Cayman/SG/OTHER/ALL）
 * 注：HKEX_CAY_NN3 已于 2026-09-21 移除——在港注册非香港公司的 NN3 周年申报由
 *     HK_NN3_AR（jurisdiction='ALL' + companyScope='HK_NON_HK'）统一覆盖，含开曼上市公司。
 *     HKEX_CAY_NN3 与 HK_NN3_AR 对同一家开曼在港注册公司会双发 NN3，故删除冗余规则。
 *
 * baseDateType:
 *   incorporationDate  → 以成立日期为基准，每年循环
 *   financialYearEnd   → 以财年结束日为基准
 *   fixed              → 固定日期（由 anchorPayload 指定）
 *                           · {m,d}：每年该月该日（如每年1月31日 → {m:1,d:31}）
 *                           · {reference:'brExpiryDate'}：以公司 brExpiryDate 为基准（BR 续期专用）
 *   trigger            → 触发式，不自动生成（持续义务 / 事件驱动）
 * baseDateOffset: 在周年/财年结束后再加N天（年为单位用 365；trigger 为 0）
 * dueDateOffset: 正数。语义按 baseDateType 区分——
 *                · fixed / reference(BR)：表示“提前N天”，引擎按 anchorDate - dueDateOffset 计算
 *                · incorporationDate / financialYearEnd：表示“截止日后再加N天”，引擎按 anchorDate + dueDateOffset 计算
 *                · trigger：表示“触发后N天”
 * anchorPayload: fixed 基准（{m,d} 或 {reference:'brExpiryDate'}）
 * condition: 补充条件（如 BVI ES 申报需 bviRelevantActivity!='none'）
 * reminderDays: 提前N天提醒（可多个）
 *
 * 注：本文件字段命名沿用服务器 complianceService 实际读取的 schema
 *     （ruleName / dueDateOffset / priority 中文 / anchorPayload / condition / specialNote），
 *     未采用早期草稿的 title / dueDaysBefore 命名。
 */
const PRESET_RULES = [
  // ── 香港非上市（8条：NAR1 / NN3 / 利得税 / BR / SCR / 变更 / 董事册 / AGM）────
  {
    ruleId: 'HK_AR_42',
    ruleName: '提交周年申报表 (NAR1)',
    description: '在公司成立周年日(Date of Anniversary)的基础上，截止日期 = 周年日 + 42天。高额罚款，并随逾期时间递增。',
    category: '公司注册处',
    legalReference: '《公司条例》第662条',
    jurisdiction: 'HK',
    companyScope: 'HK_LOCAL',   // 香港本地公司专属（NAR1）；在港注册的非香港公司走 HK_NN3_AR
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 42,
    anchorPayload: null,
    condition: '仅适用于香港本地公司（jurisdiction=HK 且 nonHongKongCompany=false）',
    reminderDays: [30, 7, 1],
    priority: '高',
    penaltyNote: '高额罚款，并随逾期时间递增',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_NN3_AR',
    ruleName: '注册非香港公司周年申报表 (NN3)',
    description: '在港注册的非香港公司（即根据《公司条例》第X部注册的海外公司）须在「周年日」后 42 天内提交 NN3 周年申报表。适用对象：公司须标记 nonHongKongCompany=true（jurisdiction 通常为 BVI/Cayman/SG/OTHER）。',
    category: '公司注册处',
    legalReference: '《公司条例》第XI部（原第 XI 部）',
    jurisdiction: 'ALL',        // 不限 jurisdiction（实务主体在港注册，但公司本身是 BVI/Cayman/...）
    companyScope: 'HK_NON_HK',  // 仅 Company.nonHongKongCompany=true 适用；与 HK_AR_42 互斥
    isListedOnly: false,
    baseDateType: 'incorporationDate',  // 锚点：境外公司在港注册日（实务可用 incorporationDate 兜底）
    baseDateOffset: 365,
    dueDateOffset: 42,
    anchorPayload: null,
    condition: '仅当 Company.nonHongKongCompany === true 时启用；与 HK_AR_42 二选一',
    reminderDays: [30, 7, 1],
    priority: '高',
    penaltyNote: '高额罚款，并随逾期时间递增；如被剔除注册须重新申请',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_TAX_1M_3M',
    ruleName: '提交利得税报税表',
    description: '利得税报税表（BIR51）一般于每年 4 月 1 日左右发出，默认发出后 1 个月提交；若委任税务代表，可按年结日享 N/D/M 整批延期（常见延后截止日为 4 月 30 日）。本规则以「每年 4 月 30 日」作为常见延后截止的规划提醒锚点（实际截止日以税表及税务代表安排为准）。',
    category: '税务局',
    legalReference: '《税务条例》第51条（利得税报税表 BIR51）',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { m: 4, d: 30 },
    baseDateOffset: 0,
    dueDateOffset: 0,   // fixed 锚点 4/30，提前 0 天 = 到期日即 4/30（规划提醒）
    condition: null,
    reminderDays: [14, 3],
    specialNote: '真实规则：BIR51 约 4/1 发出，默认 +1 个月；有税务代表按年结日整批延至 4/30。此处以 4/30 为年度规划提醒锚点，非精确法定截止日。',
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_BR_RENEW',
    ruleName: '商业登记证续期',
    description: '商业登记证到期日前必须完成续期。系统按公司 brExpiryDate 提前 30 天生成提醒。',
    category: '商业登记',
    legalReference: '《商业登记条例》',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { reference: 'brExpiryDate' },
    baseDateOffset: 0,
    dueDateOffset: 30,  // 提前 30 天（引擎按 brExpiryDate - 30 计算）
    reminderDays: [45, 15],
    priority: '紧急',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_SCR',
    ruleName: '备存重要控制人登记册 (SCR)',
    description: '须在香港注册办事处或公司秘书办事处备存重要控制人登记册，供执法人员查阅。持续义务，不自动生成。',
    category: '公司注册处',
    legalReference: '《公司条例》第653条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '中',
    specialNote: '持续备存义务，登记册须可即时查阅',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_CHANGE_NOTICE',
    ruleName: '公司变更申报（董事/秘书/地址）',
    description: '董事、公司秘书或注册地址发生变更后，须于变更后15日内呈报（表格 ND2A / ND4 等）。',
    category: '公司注册处',
    legalReference: '《公司条例》第645、652条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 15,
    anchorPayload: null,
    condition: null,
    reminderDays: [10, 3],
    priority: '高',
    specialNote: '事件驱动：变更后15日内申报',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_DIR_REG',
    ruleName: '备存董事登记册',
    description: '须备存董事登记册（含董事详情），供查阅。持续义务，不自动生成。',
    category: '公司注册处',
    legalReference: '《公司条例》第627条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_AGM',
    ruleName: '周年股东大会 (AGM)',
    description: '《公司条例》第610条：公司须于成立后18个月内举行首届周年股东大会，其后每年举行一次（每历年内举行，且前后两次 AGM 相隔不超过15个月）。本规则以「成立周年日 + 30天」作为每年一度 AGM 的规划提醒（简化，未区分首届/后续）。',
    category: '公司治理',
    legalReference: '《公司条例》第610条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 30,
    anchorPayload: null,
    condition: null,
    reminderDays: [30, 7],
    priority: '中',
    isPreset: true,
    status: '启用',
  },

  // ── BVI（5条 + 新增 册更新）────────────────────────────────
  {
    ruleId: 'BVI_ANNUAL_FEE',
    ruleName: '缴纳政府年费 (BVI)',
    description: 'BVI 年度政府规费，每年5月31日截止。逾期将导致公司除名，恢复费用高昂。',
    category: '政府规费',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { m: 5, d: 31 },
    baseDateOffset: 0,
    dueDateOffset: 60,  // 提前 60 天（引擎按 5月31日 - 60 计算）
    condition: null,
    reminderDays: [60, 30, 7],
    priority: '紧急',
    penaltyNote: '逾期将导致公司除名，恢复费用高昂',
    specialNote: '每年5月31日截止',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_ES_FILING',
    ruleName: '提交年度申报（经济实质）(BVI)',
    description: '财政年度结束日 + 约6个月（180天）。仅当公司具备经济实质相关活动（bviRelevantActivity!=\'none\'）时需申报。',
    category: '经济实质申报',
    legalReference: 'BVI Economic Substance Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 180,
    anchorPayload: null,
    condition: "bviRelevantActivity!='none'",
    reminderDays: [180, 60, 14],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_PSC',
    ruleName: '备存受益所有权登记册 (PSC)',
    description: '须通过注册代理备存可显著控制人士登记册。持续义务，不自动生成。',
    category: '受益所有权',
    legalReference: 'BVI Register of Persons with Significant Control',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '中',
    specialNote: '持续备存义务，由注册代理保管',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_BOOKS',
    ruleName: '备存账目记录 (BVI)',
    description: '须于注册代理处备存足以解释公司交易的账目记录。持续义务，不自动生成。',
    category: '账目记录',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_DIR_REG',
    ruleName: '备存董事登记册 (BVI)',
    description: '须备存董事登记册，供注册代理及执法人员查阅。持续义务，不自动生成。',
    category: '董事登记册',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_REG_UPDATE',
    ruleName: '备存册簿更新（ROM/ROD/BO）(BVI)',
    description: '股东名册(ROM)、董事名册(ROD)、实益拥有人(BO)发生变更后须于15日内更新备存。触发式，不自动生成。',
    category: '册簿备存',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 15,
    anchorPayload: null,
    condition: null,
    reminderDays: [10, 3],
    priority: '中',
    specialNote: '事件驱动：变更后15日内更新',
    isPreset: true,
    status: '启用',
  },

  // ── 开曼非上市（5条）─────────────────────────
  {
    ruleId: 'CAY_ESR',
    ruleName: '提交经济实质报告（开曼）',
    description: '财政年度结束日 + 12个月（365天）。开曼经济实质申报须于相关财年结束后 12 个月内完成。',
    category: '经济实质申报',
    legalReference: 'Cayman Islands Economic Substance Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 365,
    anchorPayload: null,
    condition: null,
    reminderDays: [270, 120, 30],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_ANNUAL_RETURN',
    ruleName: '年度申报与缴费（开曼）',
    description: '每年1月1日至1月31日期间必须完成。提前 60 天提醒。',
    category: '公司注册处年度申报',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { m: 1, d: 31 },
    baseDateOffset: 0,
    dueDateOffset: 60,  // 提前 60 天（引擎按 1月31日 - 60 计算）
    condition: null,
    reminderDays: [60, 15],   // 上年12月提醒
    priority: '紧急',
    specialNote: '每年1月1日至1月31日期间',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_PSC',
    ruleName: '备存实益拥有人登记册 (BVI/开曼)',
    description: '须通过注册代理备存实益拥有人登记册（Beneficial Ownership）。持续义务，不自动生成。',
    category: '实益拥有人',
    legalReference: 'Cayman Islands Beneficial Ownership Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '中',
    specialNote: '持续备存义务，由注册代理保管',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_BOOKS',
    ruleName: '备存账目记录 (开曼)',
    description: '须备存足以解释公司交易的账目记录。持续义务，不自动生成。',
    category: '账目记录',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_DIR_REG',
    ruleName: '备存董事登记册 (开曼)',
    description: '须备存董事登记册，供注册代理及执法人员查阅。持续义务，不自动生成。',
    category: '董事登记册',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },

  // ── 香港上市（10条：年度/中期业绩公告 + 年报/中报 + 禁售期 + 董事会通知 + 月报 + 披露）──
  {
    ruleId: 'HKEX_ANNUAL_REPORT',
    ruleName: '刊发年度报告',
    description: '财政年度结束后 4 个月内向股东送发年度报告（含年度账目及核数师报告）。等价于财年结束日 + 4 个月。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.46(2)条（主板）',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: 4,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [90, 30, 10],
    priority: '高',
    specialNote: '原文（13.46(2)(a)）：發行人須……於有關財政期間結束後（無論如何不得超過）4個月內，送交年度報告。年度「業績公告」另見 13.49(1)，須於財年結束後 3 個月內刊發（見 HKEX_ANNUAL_RESULTS）。',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_ANNUAL_RESULTS',
    ruleName: '刊发年度业绩公告（初步业绩）',
    description: '财政年度结束后 3 个月内刊发年度业绩初步公告（按《上市规则》第2.07C条尽快刊登，无论如何不得迟过财年结束后 3 个月）。等价于财年结束日 + 3 个月。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.49(1)条（主板）',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: 3,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [90, 30, 10],
    priority: '高',
    specialNote: '原文（13.49(1)）：發行人每個會計年度的初步業績須……儘快刊登，時間上無論如何不得遲過有關會計年度結束後3個月內刊登。董事禁售期（HKEX_BLACKOUT_ANNUAL）以本「公告日」為基準往前 60 天。',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INTERIM_REPORT',
    ruleName: '刊发中期报告',
    description: '上半财年结束日（即财年结束日往前 6 个月）后 3 个月内刊发中期报告。等价于财年结束日 - 3 个月。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.48(1)条（主板）',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: -3,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [30, 7, 1],
    priority: '高',
    specialNote: '原文（13.48(1)）：發行人須就每個會計年度的首6個月……發送中期報告……時間須為該6個月期間結束後的3個月內。中期「業績公告」另見 13.49(6)，須於首6個月結束後 2 個月內刊發（見 HKEX_INTERIM_RESULTS）。',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INTERIM_RESULTS',
    ruleName: '刊发中期业绩公告（初步业绩）',
    description: '上半财年结束日（财年结束日往前 6 个月）后 2 个月内刊发中期业绩初步公告（按 2.07C 条）。等价于财年结束日 - 4 个月（首6月结束 + 2月）。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.49(6)条（主板）',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: -4,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [60, 30, 10],
    priority: '高',
    specialNote: '原文（13.49(6)）：發行人須就會計年度的首6個月編制中期業績公告，並於該段6個月期間結束時起計2個月內作出公布。注意：主板自2013年起不強制季度報告（自願）；GEM 近年亦取消強制季報，故不設季度報告規則。董事禁售期（HKEX_BLACKOUT_INTERIM）以本「公告日」為基準往前 30 天。',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_MONTHLY_RETURN',
    ruleName: '提交证券变动月报表',
    description: '每月结束后第5个营业日上午8:30前向联交所提交（此处以次月第5个日历日近似）。',
    category: '持续责任披露',
    legalReference: '《上市规则》',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'fixed',   // 每月循环，后端特殊处理
    anchorPayload: { day: 5 },
    baseDateOffset: 0,
    dueDateOffset: 0,   // 次月第5日（特殊分支已锚定 day:5，offset 归零避免推到10日）
    reminderDays: [3, 1],
    priority: '高',
    specialNote: '每月提交，第5个营业日截止（此处以次月第5个日历日近似）',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INSIDE_INFO',
    ruleName: '内幕消息披露',
    description: '获悉后24小时内（"合理切实可行的范围内尽快"）。触发式任务，不自动生成。',
    category: '持续责任披露',
    legalReference: '《上市规则》第13.09条',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '紧急',
    specialNote: '触发后立即启动披露流程，不自动生成提醒',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_DIRECTOR_DISCLOSURE',
    ruleName: '董事/CEO权益披露',
    description: '权益发生变更后3个营业日内披露。',
    category: '权益披露',
    legalReference: '《证券及期货条例》第XV部',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 3,
    anchorPayload: null,
    condition: null,
    reminderDays: [1],
    priority: '高',
    specialNote: '适用于每一笔交易',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BOARD_MEETING_NOTICE',
    ruleName: '董事会会议通知（通过业绩）',
    description: '董事会会议（将批准并刊发年度/中期业绩）须于会议日期前至少 7 个营业日按《上市规则》第2.07C条刊发公告。本提醒锚定年度业绩公告截止日（FYE+3M）前约 7 营业日，提示公司秘书发出会议通知。',
    category: '董事会与公司治理',
    legalReference: '《上市规则》第13.43条',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: 3,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [21, 14, 7],
    priority: '中',
    specialNote: '原文（13.43）：發行人董事會如預期在某次會議上……通過任何年度、半年度或其他期間有關溢利或虧損的公告，發行人必須在進行該會議的至少足七個營業日之前按第2.07C條發出公告。此為規劃提醒，實際董事會日期以公司安排為準。',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BLACKOUT_ANNUAL',
    ruleName: '董事禁售期开始（年度业绩）',
    description: '年度业绩公告预计发布日前 60 天起进入董事禁售期（close period），持续至财报正式发布当日。本提醒日期为禁售期开始日（以年度业绩公告截止日 FYE+3M 为基准往前 60 天）。',
    category: '董事行为规范',
    legalReference: '《上市规则》附录十（标准守则）A.3(a)(i)；年度业绩公告见 13.49(1)',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: 3,
    dueDateOffset: -60,
    anchorPayload: null,
    condition: null,
    reminderDays: [7, 1],
    priority: '高',
    specialNote: '原文（标准守则 A.3(a)(i)）：董事在……年度業績刊發日期之前60日內……不得買賣。禁售期隨業績公告發布當日結束；如業績延遲刊發，禁售期涵蓋延遲期間。基準採年度業績公告截止日（FYE+3M）以留足安全邊際。',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BLACKOUT_INTERIM',
    ruleName: '董事禁售期开始（中期/半年度业绩）',
    description: '中期/半年度业绩公告预计发布日前 30 天起进入董事禁售期，持续至财报正式发布当日。本提醒日期为禁售期开始日（以中期业绩公告截止日 FYE-4M 为基准往前 30 天）。',
    category: '董事行为规范',
    legalReference: '《上市规则》附录十（标准守则）A.3(a)(ii)；中期业绩公告见 13.49(6)',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateUnit: 'months',
    baseDateOffset: -4,
    dueDateOffset: -30,
    anchorPayload: null,
    condition: null,
    reminderDays: [7, 1],
    priority: '高',
    specialNote: '原文（标准守则 A.3(a)(ii)）：董事在……半年度業績日期之前30日內……不得買賣。基準採中期業績公告截止日（首6月結束+2月 = FYE-4M）以留足安全邊際。',
    isPreset: true,
    status: '启用',
  },

];

module.exports = PRESET_RULES;
