/**
 * 28 条预设合规规则定义（v5.0：jurisdiction 统一为英文 HK/BVI/Cayman/SG/OTHER/ALL）
 *
 * baseDateType:
 *   incorporationDate  → 以成立日期为基准，每年循环
 *   financialYearEnd   → 以财年结束日为基准
 *   fixed              → 固定日期（由 anchorPayload 指定）
 *                           · {m,d}：每年该月该日（如每年1月31日 → {m:1,d:31}）
 *                           · {reference:'brExpiryDate'}：以公司 brExpiryDate 为基准（BR 续期专用）
 *   trigger            → 触发式，不自动生成（持续义务 / 事件驱动）
 * baseDateOffset: 在周年/财年结束后再加N天（年为单位用 365；trigger 为 0）
 * dueDateOffset: 正数。语义按 baseDateType 区分——
 *                · fixed / reference(BR)：表示“提前N天”，引擎按 anchorDate - dueDateOffset 计算
 *                · incorporationDate / financialYearEnd：表示“截止日后再加N天”，引擎按 anchorDate + dueDateOffset 计算
 *                · trigger：表示“触发后N天”
 * anchorPayload: fixed 基准（{m,d} 或 {reference:'brExpiryDate'}）
 * condition: 补充条件（如 BVI ES 申报需 bviRelevantActivity!='none'）
 * reminderDays: 提前N天提醒（可多个）
 *
 * 注：本文件字段命名沿用服务器 complianceService 实际读取的 schema
 *     （ruleName / dueDateOffset / priority 中文 / anchorPayload / condition / specialNote），
 *     未采用早期草稿的 title / dueDaysBefore 命名。
 */
const PRESET_RULES = [
  // ── 香港非上市（6条 + 新增 AGM）────────────────────────────
  {
    ruleId: 'HK_AR_42',
    ruleName: '提交周年申报表 (NAR1)',
    description: '在公司成立周年日(Date of Anniversary)的基础上，截止日期 = 周年日 + 42天。高额罚款，并随逾期时间递增。',
    category: '公司注册处',
    legalReference: '《公司条例》第662条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 42,
    anchorPayload: null,
    condition: null,
    reminderDays: [30, 7, 1],
    priority: '高',
    penaltyNote: '高额罚款，并随逾期时间递增',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_TAX_1M_3M',
    ruleName: '提交利得税报税表',
    description: '新公司：税表发出日 + 1个月；其他公司：税表发出日 + 3个月。',
    category: '税务局',
    legalReference: '《税务条例》',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 90,   // 简化：财年结束后约3个月
    anchorPayload: null,
    condition: null,
    reminderDays: [14, 3],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_BR_RENEW',
    ruleName: '商业登记证续期',
    description: '商业登记证到期日前必须完成续期。系统按公司 brExpiryDate 提前 30 天生成提醒。',
    category: '商业登记',
    legalReference: '《商业登记条例》',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { reference: 'brExpiryDate' },
    baseDateOffset: 0,
    dueDateOffset: 30,  // 提前 30 天（引擎按 brExpiryDate - 30 计算）
    reminderDays: [45, 15],
    priority: '紧急',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_SCR',
    ruleName: '备存重要控制人登记册 (SCR)',
    description: '须在香港注册办事处或公司秘书办事处备存重要控制人登记册，供执法人员查阅。持续义务，不自动生成。',
    category: '公司注册处',
    legalReference: '《公司条例》第653条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '中',
    specialNote: '持续备存义务，登记册须可即时查阅',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_CHANGE_NOTICE',
    ruleName: '公司变更申报（董事/秘书/地址）',
    description: '董事、公司秘书或注册地址发生变更后，须于变更后15日内呈报（表格 ND2A / ND4 等）。',
    category: '公司注册处',
    legalReference: '《公司条例》第645、652条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 15,
    anchorPayload: null,
    condition: null,
    reminderDays: [10, 3],
    priority: '高',
    specialNote: '事件驱动：变更后15日内申报',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_DIR_REG',
    ruleName: '备存董事登记册',
    description: '须备存董事登记册（含董事详情），供查阅。持续义务，不自动生成。',
    category: '公司注册处',
    legalReference: '《公司条例》第627条',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_AGM',
    ruleName: '周年股东大会 (AGM)',
    description: '公司成立后将尽快（不迟于成立后18个月）举行首届AGM，其后每年举行一次。基准 = 成立周年日 + 30天（简化）。',
    category: '公司治理',
    legalReference: '《公司条例》',
    jurisdiction: 'HK',
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 30,
    anchorPayload: null,
    condition: null,
    reminderDays: [30, 7],
    priority: '中',
    isPreset: true,
    status: '启用',
  },

  // ── BVI（5条 + 新增 册更新）────────────────────────────────
  {
    ruleId: 'BVI_ANNUAL_FEE',
    ruleName: '缴纳政府年费 (BVI)',
    description: 'BVI 年度政府规费，每年5月31日截止。逾期将导致公司除名，恢复费用高昂。',
    category: '政府规费',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { m: 5, d: 31 },
    baseDateOffset: 0,
    dueDateOffset: 60,  // 提前 60 天（引擎按 5月31日 - 60 计算）
    condition: null,
    reminderDays: [60, 30, 7],
    priority: '紧急',
    penaltyNote: '逾期将导致公司除名，恢复费用高昂',
    specialNote: '每年5月31日截止',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_ES_FILING',
    ruleName: '提交年度申报（经济实质）(BVI)',
    description: '财政年度结束日 + 约6个月（180天）。仅当公司具备经济实质相关活动（bviRelevantActivity!=\'none\'）时需申报。',
    category: '经济实质申报',
    legalReference: 'BVI Economic Substance Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 180,
    anchorPayload: null,
    condition: "bviRelevantActivity!='none'",
    reminderDays: [180, 60, 14],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_PSC',
    ruleName: '备存受益所有权登记册 (PSC)',
    description: '须通过注册代理备存可显著控制人士登记册。持续义务，不自动生成。',
    category: '受益所有权',
    legalReference: 'BVI Register of Persons with Significant Control',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '中',
    specialNote: '持续备存义务，由注册代理保管',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_BOOKS',
    ruleName: '备存账目记录 (BVI)',
    description: '须于注册代理处备存足以解释公司交易的账目记录。持续义务，不自动生成。',
    category: '账目记录',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_DIR_REG',
    ruleName: '备存董事登记册 (BVI)',
    description: '须备存董事登记册，供注册代理及执法人员查阅。持续义务，不自动生成。',
    category: '董事登记册',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_REG_UPDATE',
    ruleName: '备存册簿更新（ROM/ROD/BO）(BVI)',
    description: '股东名册(ROM)、董事名册(ROD)、实益拥有人(BO)发生变更后须于15日内更新备存。触发式，不自动生成。',
    category: '册簿备存',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 15,
    anchorPayload: null,
    condition: null,
    reminderDays: [10, 3],
    priority: '中',
    specialNote: '事件驱动：变更后15日内更新',
    isPreset: true,
    status: '启用',
  },

  // ── 开曼非上市（4条，已对齐 spec）─────────────────────────
  {
    ruleId: 'CAY_ESR',
    ruleName: '提交经济实质报告（开曼）',
    description: '财政年度结束日 + 约9个月（270天）。',
    category: '经济实质申报',
    legalReference: 'Cayman Islands Economic Substance Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 270,
    anchorPayload: null,
    condition: null,
    reminderDays: [270, 120, 30],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_ANNUAL_RETURN',
    ruleName: '年度申报与缴费（开曼）',
    description: '每年1月1日至1月31日期间必须完成。提前 60 天提醒。',
    category: '公司注册处年度申报',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'fixed',
    anchorPayload: { m: 1, d: 31 },
    baseDateOffset: 0,
    dueDateOffset: 60,  // 提前 60 天（引擎按 1月31日 - 60 计算）
    condition: null,
    reminderDays: [60, 15],   // 上年12月提醒
    priority: '紧急',
    specialNote: '每年1月1日至1月31日期间',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_PSC',
    ruleName: '备存实益拥有人登记册 (BVI/开曼)',
    description: '须通过注册代理备存实益拥有人登记册（Beneficial Ownership）。持续义务，不自动生成。',
    category: '实益拥有人',
    legalReference: 'Cayman Islands Beneficial Ownership Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '中',
    specialNote: '持续备存义务，由注册代理保管',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_BOOKS',
    ruleName: '备存账目记录 (开曼)',
    description: '须备存足以解释公司交易的账目记录。持续义务，不自动生成。',
    category: '账目记录',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_DIR_REG',
    ruleName: '备存董事登记册 (开曼)',
    description: '须备存董事登记册，供注册代理及执法人员查阅。持续义务，不自动生成。',
    category: '董事登记册',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: 'Cayman',
    isListedOnly: false,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '低',
    specialNote: '持续备存义务',
    isPreset: true,
    status: '启用',
  },

  // ── 香港上市（9条，baseDateType 沿用）─────────────────────
  {
    ruleId: 'HKEX_ANNUAL_REPORT',
    ruleName: '刊发年度报告',
    description: '财政年度结束日 + 4个月。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.46条',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 120,
    anchorPayload: null,
    condition: null,
    reminderDays: [90, 30, 10],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INTERIM_REPORT',
    ruleName: '刊发中期报告',
    description: '中期期间结束日 + 3个月（一般为财年上半年末+3个月）。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.48条',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: -180,  // 财年半程
    dueDateOffset: 90,
    anchorPayload: null,
    condition: null,
    reminderDays: [60, 30, 10],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_Q_REPORT',
    ruleName: '刊发季度报告（如适用）',
    description: '季度结束日 + 45天。',
    category: '定期财务报告',
    legalReference: '《上市规则》',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: -270,
    dueDateOffset: 45,
    anchorPayload: null,
    condition: null,
    reminderDays: [30, 15, 5],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_MONTHLY_RETURN',
    ruleName: '提交证券变动月报表',
    description: '每月结束后第5个营业日上午8:30前向联交所提交。',
    category: '持续责任披露',
    legalReference: '《上市规则》',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'fixed',   // 每月循环，后端特殊处理
    anchorPayload: { day: 5 },
    baseDateOffset: 0,
    dueDateOffset: 5,
    reminderDays: [3, 1],
    priority: '高',
    specialNote: '每月提交，第5个营业日截止',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INSIDE_INFO',
    ruleName: '内幕消息披露',
    description: '获悉后24小时内（"合理切实可行的范围内尽快"）。触发式任务，不自动生成。',
    category: '持续责任披露',
    legalReference: '《上市规则》第13.09条',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    anchorPayload: null,
    condition: null,
    reminderDays: [],
    priority: '紧急',
    specialNote: '触发后立即启动披露流程，不自动生成提醒',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_DIRECTOR_DISCLOSURE',
    ruleName: '董事/CEO权益披露',
    description: '权益发生变更后3个营业日内披露。',
    category: '权益披露',
    legalReference: '《证券及期货条例》第XV部',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 3,
    anchorPayload: null,
    condition: null,
    reminderDays: [1],
    priority: '高',
    specialNote: '适用于每一笔交易',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BOARD_MEETING_NOTICE',
    ruleName: '董事会会议通知（用于通过业绩）',
    description: '会议日期前至少7个营业日通知联交所。',
    category: '董事会与公司治理',
    legalReference: '《上市规则》',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 100,   // 大约在发布年报前
    anchorPayload: null,
    condition: null,
    reminderDays: [10],
    priority: '中',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BLACKOUT_ANNUAL',
    ruleName: '董事禁售期（年度业绩）',
    description: '年度业绩预计发布日前60天至财报正式发布当日，禁止所有董事及关联人士买卖股份。',
    category: '董事行为规范',
    legalReference: '《上市规则》附录十',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 120,
    anchorPayload: null,
    condition: null,
    reminderDays: [7],
    priority: '高',
    specialNote: '此期间禁止买卖公司股份，需提前通知所有董事',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BLACKOUT_INTERIM',
    ruleName: '董事禁售期（中期/季度业绩）',
    description: '中期/季度业绩预计发布日前30天至财报正式发布当日，禁止董事买卖股份。',
    category: '董事行为规范',
    legalReference: '《上市规则》附录十',
    jurisdiction: 'HK',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: -180,
    dueDateOffset: 90,
    anchorPayload: null,
    condition: null,
    reminderDays: [7],
    priority: '高',
    isPreset: true,
    status: '启用',
  },

  // ── 特殊（1条）──────────────────────────────────────────
  {
    ruleId: 'HKEX_CAY_NN3',
    ruleName: '提交周年申报表（表格NN3，在港上市开曼公司）',
    description: '在港上市的开曼公司须向香港公司注册处提交NN3表格，截止日期 = 成立周年日 + 42天。',
    category: '公司注册处（香港）',
    legalReference: '《公司条例》',
    jurisdiction: 'Cayman',
    isListedOnly: true,
    listingLocation: 'HK',
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 42,
    anchorPayload: null,
    condition: null,
    reminderDays: [30, 7, 1],
    priority: '高',
    specialNote: '独立于开曼本地年检的香港法定义务',
    isPreset: true,
    status: '启用',
  },
];

module.exports = PRESET_RULES;
