/**
 * 17 条预设合规规则定义
 * baseDateType:
 *   incorporationDate  → 以成立日期为基准，每年循环
 *   financialYearEnd   → 以财年结束日为基准
 *   fixed              → 固定日期（如每年1月31日）
 *   trigger            → 触发式，不自动生成
 * dueDateOffset: 在周年/财年结束后再加N天
 * reminderDays: 提前N天提醒（可多个）
 */
const PRESET_RULES = [
  // ── 香港非上市（3条）──────────────────────────────────────
  {
    ruleId: 'HK_AR_42',
    ruleName: '提交周年申报表 (NAR1)',
    description: '在公司成立周年日(Date of Anniversary)的基础上，截止日期 = 周年日 + 42天。高额罚款，并随逾期时间递增。',
    category: '公司注册处',
    legalReference: '《公司条例》第662条',
    jurisdiction: '香港',
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 42,
    reminderDays: [30, 7, 1],
    priority: '高',
    penaltyNote: '高额罚款，并随逾期时间递增',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_TAX_1M_3M',
    ruleName: '提交利得税报税表',
    description: '新公司：税表发出日 + 1个月；其他公司：税表发出日 + 3个月。',
    category: '税务局',
    legalReference: '《税务条例》',
    jurisdiction: '香港',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 90,   // 简化：财年结束后约3个月
    reminderDays: [14, 3],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HK_BR_RENEW',
    ruleName: '商业登记证续期',
    description: '到期日前必须完成续期。系统每年自动根据上次续期日+1年生成新任务。',
    category: '商业登记',
    legalReference: '《商业登记条例》',
    jurisdiction: '香港',
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 0,
    reminderDays: [45, 15],
    priority: '高',
    isPreset: true,
    status: '启用',
  },

  // ── BVI（2条）──────────────────────────────────────────────
  {
    ruleId: 'BVI_ANNUAL_FEE',
    ruleName: '缴纳政府年费 (BVI)',
    description: '注册月份1-6月：当年5月31日；注册月份7-12月：当年11月30日。逾期将导致公司除名，恢复费用高昂。',
    category: '政府规费',
    legalReference: 'BVI Business Companies Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'incorporationDate',
    baseDateOffset: 0,
    dueDateOffset: 0,   // 实际由服务层按注册月份动态计算
    reminderDays: [60, 30, 7],
    priority: '高',
    penaltyNote: '逾期将导致公司除名，恢复费用高昂',
    specialNote: '注册月份1-6月截止5月31日；7-12月截止11月30日',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'BVI_ES_FILING',
    ruleName: '提交年度申报（经济实质）(BVI)',
    description: '财政年度结束日 + 9个月。',
    category: '经济实质申报',
    legalReference: 'BVI Economic Substance Act',
    jurisdiction: 'BVI',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 270,  // 9个月≈270天
    reminderDays: [180, 60, 14],
    priority: '高',
    isPreset: true,
    status: '启用',
  },

  // ── 开曼非上市（2条）──────────────────────────────────────
  {
    ruleId: 'CAY_ESR',
    ruleName: '提交经济实质报告（开曼）',
    description: '财政年度结束日 + 12个月。',
    category: '经济实质申报',
    legalReference: 'Cayman Islands Economic Substance Act',
    jurisdiction: '开曼',
    isListedOnly: false,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 365,
    reminderDays: [270, 120, 30],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'CAY_ANNUAL_RETURN',
    ruleName: '年度申报与缴费（开曼）',
    description: '每年1月1日至1月31日期间必须完成。',
    category: '公司注册处年度申报',
    legalReference: 'Cayman Islands Companies Act',
    jurisdiction: '开曼',
    isListedOnly: false,
    baseDateType: 'fixed',
    baseDateOffset: 0,
    dueDateOffset: 31,   // 每年1月31日
    reminderDays: [60, 15],   // 上年12月提醒
    priority: '高',
    specialNote: '每年1月1日至1月31日期间',
    isPreset: true,
    status: '启用',
  },

  // ── 香港上市（9条）────────────────────────────────────────
  {
    ruleId: 'HKEX_ANNUAL_REPORT',
    ruleName: '刊发年度报告',
    description: '财政年度结束日 + 4个月。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.46条',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 120,
    reminderDays: [90, 30, 10],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INTERIM_REPORT',
    ruleName: '刊发中期报告',
    description: '中期期间结束日 + 3个月（一般为财年上半年末+3个月）。',
    category: '定期财务报告',
    legalReference: '《上市规则》第13.48条',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: -180,  // 财年半程
    dueDateOffset: 90,
    reminderDays: [60, 30, 10],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_Q_REPORT',
    ruleName: '刊发季度报告（如适用）',
    description: '季度结束日 + 45天。',
    category: '定期财务报告',
    legalReference: '《上市规则》',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: -270,
    dueDateOffset: 45,
    reminderDays: [30, 15, 5],
    priority: '高',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_MONTHLY_RETURN',
    ruleName: '提交证券变动月报表',
    description: '每月结束后第5个营业日上午8:30前向联交所提交。',
    category: '持续责任披露',
    legalReference: '《上市规则》',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'fixed',   // 每月循环，后端特殊处理
    baseDateOffset: 0,
    dueDateOffset: 5,
    reminderDays: [3, 1],
    priority: '高',
    specialNote: '每月提交，第5个营业日截止',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_INSIDE_INFO',
    ruleName: '内幕消息披露',
    description: '获悉后24小时内（"合理切实可行的范围内尽快"）。触发式任务，不自动生成。',
    category: '持续责任披露',
    legalReference: '《上市规则》第13.09条',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 0,
    reminderDays: [],
    priority: '紧急',
    specialNote: '触发后立即启动披露流程，不自动生成提醒',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_DIRECTOR_DISCLOSURE',
    ruleName: '董事/CEO权益披露',
    description: '权益发生变更后3个营业日内披露。',
    category: '权益披露',
    legalReference: '《证券及期货条例》第XV部',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'trigger',
    baseDateOffset: 0,
    dueDateOffset: 3,
    reminderDays: [1],
    priority: '高',
    specialNote: '适用于每一笔交易',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BOARD_MEETING_NOTICE',
    ruleName: '董事会会议通知（用于通过业绩）',
    description: '会议日期前至少7个营业日通知联交所。',
    category: '董事会与公司治理',
    legalReference: '《上市规则》',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 100,   // 大约在发布年报前
    reminderDays: [10],
    priority: '中',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BLACKOUT_ANNUAL',
    ruleName: '董事禁售期（年度业绩）',
    description: '年度业绩预计发布日前60天至财报正式发布当日，禁止所有董事及关联人士买卖股份。',
    category: '董事行为规范',
    legalReference: '《上市规则》附录十',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: 0,
    dueDateOffset: 120,
    reminderDays: [7],
    priority: '高',
    specialNote: '此期间禁止买卖公司股份，需提前通知所有董事',
    isPreset: true,
    status: '启用',
  },
  {
    ruleId: 'HKEX_BLACKOUT_INTERIM',
    ruleName: '董事禁售期（中期/季度业绩）',
    description: '中期/季度业绩预计发布日前30天至财报正式发布当日，禁止董事买卖股份。',
    category: '董事行为规范',
    legalReference: '《上市规则》附录十',
    jurisdiction: '香港',
    isListedOnly: true,
    baseDateType: 'financialYearEnd',
    baseDateOffset: -180,
    dueDateOffset: 90,
    reminderDays: [7],
    priority: '高',
    isPreset: true,
    status: '启用',
  },

  // ── 特殊（1条）──────────────────────────────────────────
  {
    ruleId: 'HKEX_CAY_NN3',
    ruleName: '提交周年申报表（表格NN3，在港上市开曼公司）',
    description: '在港上市的开曼公司须向香港公司注册处提交NN3表格，截止日期 = 成立周年日 + 42天。',
    category: '公司注册处（香港）',
    legalReference: '《公司条例》',
    jurisdiction: '开曼',
    isListedOnly: true,
    listingLocation: 'HK',
    baseDateType: 'incorporationDate',
    baseDateOffset: 365,
    dueDateOffset: 42,
    reminderDays: [30, 7, 1],
    priority: '高',
    specialNote: '独立于开曼本地年检的香港法定义务',
    isPreset: true,
    status: '启用',
  },
];

module.exports = PRESET_RULES;
