/**
 * 合规闭环第二跳：Reminder → Task
 *
 * 将一条合规提醒派生为一条可追溯的 Task：
 *  - title/description/company/dueDate 取自提醒；
 *  - priority 由中文枚举映射为英文枚举（高→high 等）；
 *  - 反向写回 reminder.task，使前端既有的「↗ 任务」跳转生效；
 *  - 幂等：同一提醒已生成过任务则直接返回已存在任务，避免重复 spawn。
 */
const Task = require('../models/Task');
const ComplianceReminder = require('../models/ComplianceReminder');

const PRIORITY_MAP = { '高': 'high', '中': 'medium', '低': 'low', '紧急': 'urgent' };

function toObjectIdOrNull(v) {
  if (!v) return null;
  // populate 后可能是对象（含 _id），也可能仍是 ObjectId
  return v && v._id ? v._id : v;
}

/**
 * 为单条提醒生成关联 Task。
 * @returns {Promise<{task:Object, created:boolean}>}
 */
async function createTaskFromReminder(reminderId, { userId, assignedTo = [], notes = '' } = {}) {
  const reminder = await ComplianceReminder.findById(reminderId)
    .populate('company', 'name nameChinese jurisdiction')
    .populate('rule', 'ruleName ruleId category');
  if (!reminder) throw new Error('Reminder not found');

  // 幂等：该提醒已生成过任务 → 返回已存在任务
  const existing = await Task.findOne({ complianceReminder: reminder._id });
  if (existing) return { task: existing, created: false };

  const rule = reminder.rule;
  const task = await Task.create({
    title: reminder.title,
    description: reminder.description || '',
    type: 'compliance',
    company: toObjectIdOrNull(reminder.company),
    priority: PRIORITY_MAP[reminder.priority] || 'medium',
    status: 'pending',
    dueDate: reminder.dueDate,
    startDate: new Date(),
    assignedTo: Array.isArray(assignedTo) ? assignedTo : [],
    notes: notes ? [{ content: notes }] : [],
    createdBy: userId,
    autoGenerated: true,
    complianceReminder: reminder._id,
    complianceRule: toObjectIdOrNull(rule) || reminder.rule,
    complianceRuleId: reminder.ruleId || (rule && rule.ruleId),
  });

  // 反向写回，让前端既有 r.task 跳转生效
  reminder.task = task._id;
  await reminder.save();

  return { task, created: true };
}

/**
 * 批量生成。逐条容错，返回每条结果与汇总。
 */
async function createTasksBatch(ids, opts = {}) {
  const results = [];
  for (const id of ids || []) {
    try {
      const r = await createTaskFromReminder(id, opts);
      results.push({ reminderId: id, taskId: r.task._id, created: r.created, status: 'ok' });
    } catch (err) {
      results.push({ reminderId: id, status: 'error', message: err.message });
    }
  }
  const created = results.filter((r) => r.created).length;
  const skipped = results.filter((r) => r.status === 'ok' && !r.created).length;
  const errors = results.filter((r) => r.status === 'error').length;
  return { results, created, skipped, errors };
}

module.exports = { createTaskFromReminder, createTasksBatch, PRIORITY_MAP };
