module.exports = {
 "interimOffsets": [
  {
   "key": "blackout",
   "name": "禁售期启动",
   "anchor": "T1",
   "days": -30,
   "rule": "附录10 A.3：中期业绩公告前30天内董事不得买卖",
   "note": "默认-30；保守可改-45；按公司合规手册"
  },
  {
   "key": "ff05",
   "name": "FF05报备",
   "anchor": "T1",
   "days": -32,
   "rule": "上市规则13.06+附录10：禁售期须书面通知HKEX",
   "note": "FF05须禁售期开始前提交；预留2个工作日"
  },
  {
   "key": "profitwarn",
   "name": "盈警/盈喜判断截止",
   "anchor": "T1",
   "days": -5,
   "rule": "上市规则13.49(2)延伸至中期：重大变化须尽快刊发盈利预告",
   "note": "T1前5天最后判断窗口；变化>20%立即起草"
  },
  {
   "key": "audit_in",
   "name": "审计进场",
   "anchor": "T1",
   "days": -50,
   "rule": "审计实务：中期审阅(review)工作量较审计小",
   "note": "T1-50=7/1进场；足够完成分析程序"
  },
  {
   "key": "review_done",
   "name": "审阅程序完成",
   "anchor": "T1",
   "days": -10,
   "rule": "审计实务：中期财务资料须经核数师审阅(review level)",
   "note": "T1-10=8/10完成审阅程序"
  },
  {
   "key": "review_report",
   "name": "审阅报告出具",
   "anchor": "T1",
   "days": -7,
   "rule": "核数师须就中期财务资料出具审阅报告",
   "note": "T1-7=8/13出具；AC会议前到位"
  },
  {
   "key": "mda",
   "name": "MD&A定稿",
   "anchor": "T1",
   "days": -5,
   "rule": "上市规则13.48附录D：中期MD&A须含简明持续经营段",
   "note": "T1-5=8/15定稿；含持续经营段"
  },
  {
   "key": "ac_material",
   "name": "审核委材料",
   "anchor": "T1",
   "days": -7,
   "rule": "CG守则C.3.3：审核委员会须审阅中期财务资料",
   "note": "T1-7=8/13交AC；同日或次日开AC会"
  },
  {
   "key": "internal_ctrl",
   "name": "内控简报",
   "anchor": "T1",
   "days": -9,
   "rule": "CG守则：中期提交内控简报供AC审阅",
   "note": "T1-9=8/11交；提前给AC委员看"
  },
  {
   "key": "board_notice",
   "name": "董事会通告",
   "anchor": "T1",
   "days": -10,
   "rule": "公司章程：董事会会议通告须于至少7-14天前发出",
   "note": "T1-10=8/10发通告；含周末10天"
  },
  {
   "key": "board_ann",
   "name": "董事会会议日期公告",
   "anchor": "T1",
   "days": -10,
   "rule": "上市规则第13.43条：董事会会议日期的公告须于董事会前至少7个工作天前上载联交所网站（经ESS）及本公司网站",
   "note": "T1-10=8/10或之前；与董事通告分开"
  },
  {
   "key": "board_mat",
   "name": "董事会材料定稿",
   "anchor": "T1",
   "days": -2,
   "rule": "上市规则13.48：董事会须批准中期业绩公告/中报/股息",
   "note": "T1-2=8/18定稿发送全体董事"
  },
  {
   "key": "framework",
   "name": "中期报告框架传阅",
   "anchor": "T1",
   "days": -14,
   "rule": "实务：中报框架提前传阅审计/印刷商/律师协调时间",
   "note": "T1-14=8/6开始传阅；印刷商9/14要IR cover"
  },
  {
   "key": "print_submit",
   "name": "提交印刷商排版翻译",
   "anchor": "T1",
   "days": -20,
   "rule": "预留至少十个工作天予印刷商进行排版及翻译工作",
   "note": "T1-20=7/31或之前；交付全文中英文"
  },
  {
   "key": "confirm_qty",
   "name": "确认印数",
   "anchor": "T1",
   "days": 19,
   "rule": "付印前须与印刷商确认中期报告印数",
   "note": "T1+19=9/8；付印前确认"
  },
  {
   "key": "ir_cover",
   "name": "IR封面预印交付",
   "anchor": "T2",
   "days": -8,
   "rule": "印刷商要求：9/14 18:00前提供IR cover数量",
   "note": "T2-8=9/14 18:00；对应印刷商pre-print节点"
  },
  {
   "key": "ec_letters",
   "name": "E&C信函定稿",
   "anchor": "T2",
   "days": -8,
   "rule": "印刷商要求：9/14 23:59前Sign off E&C Letters",
   "note": "T2-8=9/14 23:59；律师(E&C)定稿硬deadline"
  },
  {
   "key": "deliver_letters",
   "name": "信函交付过户处",
   "anchor": "T2",
   "days": -5,
   "rule": "印刷商要求：9/17 10:00前Deliver Letters to share registrar",
   "note": "T2-5=9/17 10:00；过户处Tricor"
  },
  {
   "key": "text_final",
   "name": "中期报告正文定稿",
   "anchor": "T2",
   "days": -5,
   "rule": "印刷商要求：9/17 23:59前Sign off E&C IR Text(all)",
   "note": "★最关键的定稿deadline"
  },
  {
   "key": "printing",
   "name": "中报付印",
   "anchor": "T2",
   "days": -5,
   "rule": "印刷实务：中报付印与正文定稿同步（定稿即付印）",
   "note": "T2-5=9/17；与正文定稿同日；预留5天给印刷"
  },
  {
   "key": "ir_deliver",
   "name": "IR交付过户处",
   "anchor": "T2",
   "days": -1,
   "rule": "印刷商要求：9/22 10:00前Deliver IR to share registrar",
   "note": "T2-1=9/21；但印刷商写9/22 10:00"
  },
  {
   "key": "ess_upload",
   "name": "中期报告上传ESS",
   "anchor": "T2",
   "days": 0,
   "rule": "上市规则13.46(2)+印刷商：9/22 after hours e-submission",
   "note": "T2=9/22收盘后ESS上传；23:59前完成"
  },
  {
   "key": "despatch",
   "name": "寄发日(Despatch)",
   "anchor": "T2",
   "days": 1,
   "rule": "印刷商：9/23 Despatch by share registrar",
   "note": "T2+1=9/23；过户处寄发日（非法规节点）"
  },
  {
   "key": "dividend_pay",
   "name": "派发股息支票",
   "anchor": "T2",
   "days": 8,
   "rule": "（如有）中期股息须于董事会建议派发后寄发；实务约T2+8",
   "note": "T2+8=9/30或之前；依股息政策"
  }
 ],
 "annualOffsets": [
  {
   "key": "blackout",
   "name": "禁售期启动",
   "anchor": "T1",
   "days": -60,
   "rule": "附录10 A.3：在年度业绩公告前60天内，董事不得买卖公司证券",
   "note": "默认-60；不成熟可改-65提前；天数不得大于-60"
  },
  {
   "key": "ff05",
   "name": "FF05报备",
   "anchor": "T1",
   "days": -62,
   "rule": "上市规则13.06+附录10：发行人须书面通知联交所有关禁止买卖期安排",
   "note": "FF05须禁售期开始前提交，预留2个工作日给联交所"
  },
  {
   "key": "profitwarn",
   "name": "盈警/盈喜判断截止",
   "anchor": "T1",
   "days": -7,
   "rule": "上市规则13.49(2)：重大变化须尽快刊发盈利警告或正面盈利预告",
   "note": "T1前7天最后判断窗口；越早越好避免内幕消息泄露"
  },
  {
   "key": "audit_in",
   "name": "审计进场",
   "anchor": "T1",
   "days": -90,
   "rule": "审计实务：核数师须有足够时间完成审计程序",
   "note": "大公司可-100；小公司-75亦可；视审计复杂度"
  },
  {
   "key": "audit_draft_done",
   "name": "审计底稿完成",
   "anchor": "T1",
   "days": -20,
   "rule": "审计实务+13.49：审计底稿完成是初稿前提",
   "note": "底稿后还需经理/合伙人两级复核，留足缓冲"
  },
  {
   "key": "audit_draft",
   "name": "审计初稿",
   "anchor": "T1",
   "days": -17,
   "rule": "审计实务：初稿交公司秘书起草公告",
   "note": "初稿到定稿3-5天；重大调整多留时间"
  },
  {
   "key": "mda",
   "name": "MD&A定稿",
   "anchor": "T1",
   "days": -7,
   "rule": "上市规则13.49附录D：管理层讨论须含持续经营段",
   "note": "MD&A用初稿起草，定稿前1天最后核对；含持续经营段"
  },
  {
   "key": "board_notice",
   "name": "董事会通告",
   "anchor": "T1",
   "days": -14,
   "rule": "公司章程：定期董事会会议通告须于至少14天前发出",
   "note": "章程若要求21天按章程；含周末计算"
  },
  {
   "key": "ac_material",
   "name": "审核委材料",
   "anchor": "T1",
   "days": -7,
   "rule": "CG守则C.3.3：审核委员会须在年报前审阅财务资料",
   "note": "其中一次管理层不在场；材料提前一周交委员"
  },
  {
   "key": "internal_ctrl",
   "name": "内控报告",
   "anchor": "T1",
   "days": -9,
   "rule": "CG守则C.3+风险管理守则：内控报告须提前交审核委审阅",
   "note": "提前一周给委员审阅，留2天Q&A"
  },
  {
   "key": "auditor_letter",
   "name": "核数师函件",
   "anchor": "T1",
   "days": -6,
   "rule": "审计实务+CG守则：审核情况说明函件须董事会前交到",
   "note": "最晚T1-6天；核数师延迟整条链都会卡"
  },
  {
   "key": "board_mat",
   "name": "董事会材料定稿",
   "anchor": "T1",
   "days": -2,
   "rule": "实务：中英文公告、审计报告、CG、ESG、AGM通告、股息表须T1前送达董事",
   "note": "T1前2天全体董事收到；境外董事考虑时差"
  },
  {
   "key": "annual_print",
   "name": "年报付印",
   "anchor": "T2",
   "days": -3,
   "rule": "印刷实务：印刷+送过户处+上传ESS需3个工作日",
   "note": "T2为上传日，付印须提前；有修订多留1天"
  },
  {
   "key": "rh_nrh",
   "name": "RH/NRH定稿",
   "anchor": "T2",
   "days": -5,
   "rule": "上市规则13.46：RH Letter(送年报通知)/NRH Letter(不送通知)须定稿",
   "note": "含中英文伴送声明；无纸化机制语句要嵌"
  },
  {
   "key": "ess_a",
   "name": "年报上传ESS",
   "anchor": "T2",
   "days": 0,
   "rule": "上市规则13.46(1)：年报须在财年结束后4个月内上传ESS及公司网站",
   "note": "T2当日或提前1天；分类选Financial Statements/ESG"
  },
  {
   "key": "suspend_notice",
   "name": "暂停过户通知",
   "anchor": "T3",
   "days": -31,
   "rule": "上市规则13.66(1)：暂停股份过户登记前至少10个营业日书面通知",
   "note": "T3-21天-10营业日≈T3-31天；须同时通知HKEX和过户处"
  },
  {
   "key": "suspend_start",
   "name": "暂停过户开始",
   "anchor": "T3",
   "days": -6,
   "rule": "公司章程第47条：全年暂停登记不超30天；AGM通常4个工作日",
   "note": "含AGM当日在内；计算时扣除周末"
  },
  {
   "key": "proxy_deadline",
   "name": "代表委任表截止",
   "anchor": "T3",
   "days": -2,
   "rule": "公司章程：代表委任表须于AGM前48小时送达",
   "note": "T3-2天；章程更严格则按章程"
  },
  {
   "key": "if001",
   "name": "IF001提交",
   "anchor": "T3",
   "days": -25,
   "rule": "上市规则13.39+ESS操作：IF001报备最终AGM时间",
   "note": "T4确定后即可提交；最迟T3-7天"
  },
  {
   "key": "vote_result",
   "name": "投票结果上传",
   "anchor": "T3",
   "days": 0,
   "rule": "上市规则13.39(4)：AGM后须于当晚11时前上传投票结果公告",
   "note": "T3当日23:00前；模板提前备好"
  },
  {
   "key": "agm_record",
   "name": "AGM记录呈交",
   "anchor": "T3",
   "days": 15,
   "rule": "上市规则13.66(2)：AGM后15天内呈交会议记录核证本",
   "note": "T3+15天；含INED出席比例+法定人数"
  }
 ],
 "interimTasks": [
  {
   "cat": "中期业绩",
   "rule": "附录10 A.3：中期业绩公告前30天内董事不得买卖；13.06须书面通知HKEX",
   "title": "禁止买卖期启动+FF05通知HKEX（覆盖1321/2271/672）",
   "steps": "1)T1-30天为禁售期首日 2)制备FF05(三家公司分别或合并) 3)提交HKEX并抄送全体董事 4)同步通知有关雇员 5)IM登记册记录",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "林才贺",
   "agency": "律师(WFW)",
   "sKey": "blackout",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "blackout",
   "eWorkday": false,
   "eDelta": 0,
   "file": "FF005(中期)",
   "note": "T1-30=7/21;三家公司"
  },
  {
   "cat": "中期业绩",
   "rule": "上市规则13.49(2)延伸至中期：重大变化须尽快刊发盈利预告",
   "title": "监察是否须发出盈警/盈喜公告（截至T1-5天）",
   "steps": "1)8/15前审阅中期损益表 2)对比去年同期/市场预期 3)变化>20%立即起草盈警/盈喜 4)经律师+审计复核后刊发",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "林才贺/李云巧",
   "agency": "律师",
   "sKey": "profitwarn",
   "sWorkday": true,
   "sDelta": -7,
   "eKey": "profitwarn",
   "eWorkday": false,
   "eDelta": 0,
   "file": "盈利预告公告",
   "note": "T1-5=8/15最后判断窗口"
  },
  {
   "cat": "中期业绩",
   "rule": "审计实务+HKSA 240：中期财务资料须经核数师审阅(review level)",
   "title": "中期审阅（进场→程序→审阅报告·覆盖三家公司）",
   "steps": "1)T1-50天=7/1审计进场 2)执行分析程序+有限测试 3)T1-7天=8/13出具审阅报告 4)审阅报告附公告",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "汤锦涛/高国萍",
   "agency": "EY安永",
   "sKey": "audit_in",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "review_report",
   "eWorkday": false,
   "eDelta": 0,
   "file": "审阅报告",
   "note": "T1-50=7/1;T1-7=8/13"
  },
  {
   "cat": "中期业绩",
   "rule": "审计实务+CG守则C.3.3：核数师须向审核委员会提交中期审阅情况说明",
   "title": "核数师《中期审阅情况说明》+意见类型跟踪",
   "steps": "1)要求EY在8/13前交审阅报告 2)核对审阅意见类型 3)若有保留事项立即评估 4)归档",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "李云巧/汤锦涛",
   "agency": "EY安永",
   "sKey": "review_report",
   "sWorkday": true,
   "sDelta": -3,
   "eKey": "review_report",
   "eWorkday": false,
   "eDelta": 0,
   "file": "审阅情况说明",
   "note": "AC会议前到位"
  },
  {
   "cat": "中期业绩",
   "rule": "上市规则13.48附录D：中期MD&A须含简明持续经营段及重大变动说明",
   "title": "管理层讨论及分析(中期MD&A)+持续经营段（中英文）",
   "steps": "1)基于审阅后数字起草MD&A 2)简明持续经营段(引用年度假设) 3)解释重大变动(>10%) 4)中英文双语",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "汤锦涛/高国萍/李云巧",
   "agency": "内部",
   "sKey": "mda",
   "sWorkday": true,
   "sDelta": -3,
   "eKey": "mda",
   "eWorkday": false,
   "eDelta": 0,
   "file": "中期公告(中/英)",
   "note": "T1-5=8/15定稿"
  },
  {
   "cat": "中期业绩",
   "rule": "上市规则13.46(2)+实务：中期业绩公告与中期报告数字须一致",
   "title": "中期业绩vs中期报告数据一致性核对（双签）",
   "steps": "1)建Checklist列出关键数字(营收/利润/资产/负债) 2)财务负责人逐数核对 3)公司秘书复核 4)双签确认后付印",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "李云巧",
   "agency": "内部",
   "sKey": "text_final",
   "sWorkday": true,
   "sDelta": -10,
   "eKey": "text_final",
   "eWorkday": false,
   "eDelta": 0,
   "file": "Sign-off Checklist",
   "note": "T2-10=9/12开始核对"
  },
  {
   "cat": "中期业绩",
   "rule": "内幕消息规定：发行人对内幕消息须备存书面记录",
   "title": "内幕消息登记册(IM Register)更新",
   "steps": "1)禁售期通知 2)董事沟通记录 3)盈警判断过程 4)统一入IM登记册按月归档",
   "pri": "中优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "林才贺",
   "agency": "内部",
   "sKey": "ff05",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "ff05",
   "eWorkday": false,
   "eDelta": 0,
   "file": "IM Register",
   "note": "与年度同机制"
  },
  {
   "cat": "中期业绩",
   "rule": "附录10+第10章：中期董事会为业绩开会前1个月至公告日禁回购",
   "title": "回购静默期冲突检查（三家公司分别查）",
   "steps": "1)确认各公司是否有回购授权 2)T1前1个月(7/21)起禁回购 3)检查现有授权余额 4)通知有关雇员 5)至T1(8/20)公告日止",
   "pri": "中优",
   "status": "未启动",
   "proj": "中期业绩",
   "owner": "林才贺",
   "agency": "内部",
   "sKey": "blackout",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "T1",
   "eWorkday": false,
   "eDelta": 0,
   "file": "回购授权文件",
   "note": "无回购授权则跳过"
  },
  {
   "cat": "审核委员会",
   "rule": "CG守则C.3.3：审核委员会须审阅中期财务资料；中期至少一次",
   "title": "审核委员会审阅中期财务资料（AC会议）",
   "steps": "1)T1-7天=8/13前交AC材料 2)安排AC会议(8/13或8/14) 3)形成决议 4)记录归档",
   "pri": "最高优",
   "status": "未启动",
   "proj": "董事会",
   "owner": "林才贺",
   "agency": "EY安永",
   "sKey": "ac_material",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "ac_material",
   "eWorkday": false,
   "eDelta": 0,
   "file": "AC决议",
   "note": "T1-7=8/13;一次即可"
  },
  {
   "cat": "审核委员会",
   "rule": "CG守则C.3.3(b)：AC须与核数师讨论审阅范围及结果",
   "title": "AC与核数师中期会议（可管理层在场）",
   "steps": "1)安排会议 2)讨论审阅发现/调整事项/持续经营 3)记录会议纪要 4)归档",
   "pri": "高优",
   "status": "未启动",
   "proj": "董事会",
   "owner": "林才贺",
   "agency": "EY安永",
   "sKey": "ac_material",
   "sWorkday": true,
   "sDelta": -2,
   "eKey": "ac_material",
   "eWorkday": false,
   "eDelta": 0,
   "file": "AC会议纪要",
   "note": "中期可与管理层在场"
  },
  {
   "cat": "董事会",
   "rule": "公司章程+上市规则13.48：董事会须批准中期业绩公告及中期报告",
   "title": "董事会议程传送+通告发出(≥10天·三家公司分别)",
   "steps": "1)确定各公司董事会日期(1321/2271=8/20,672=8/21) 2)制备通告及议程 3)电子邮件+书面发送 4)确认收悉",
   "pri": "高优",
   "status": "未启动",
   "proj": "董事会",
   "owner": "林才贺",
   "agency": "内部人力行政",
   "sKey": "board_notice",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "board_notice",
   "eWorkday": false,
   "eDelta": 0,
   "file": "董事会通告/议程",
   "note": "T1-10=8/10发通告"
  },
  {
   "cat": "董事会",
   "rule": "CG守则+风险管理守则：中期提交内控简报供AC/董事会审阅",
   "title": "内控简报提交AC/董事会（提前一周）",
   "steps": "1)T1-9天=8/11前准备内控简报 2)重点写上半年内控缺陷及整改 3)交AC审阅 4)纳入董事会材料",
   "pri": "中优",
   "status": "未启动",
   "proj": "董事会",
   "owner": "李云巧/林才贺",
   "agency": "内部审计部门",
   "sKey": "internal_ctrl",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "internal_ctrl",
   "eWorkday": false,
   "eDelta": 0,
   "file": "内控简报",
   "note": "T1-9=8/11;简报非完整报告"
  },
  {
   "cat": "董事会",
   "rule": "上市规则13.48：董事会须批准中期业绩公告/中报/股息建议(如有)",
   "title": "收集及传阅董事会材料+草拟会议纪要（1321/2271/672分别）",
   "steps": "1)汇编材料(议程/审阅报告/业绩公告中英文/MD&A/内控简报/股息计算) 2)T1-2天=8/18定稿发送 3)会后草拟纪要",
   "pri": "最高优",
   "status": "未启动",
   "proj": "董事会",
   "owner": "林才贺/李云巧",
   "agency": "内部",
   "sKey": "board_mat",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "board_mat",
   "eWorkday": false,
   "eDelta": 0,
   "file": "董事会材料全套",
   "note": "T1-2=8/18;三家公司分别"
  },
  {
   "cat": "董事会",
   "rule": "上市规则第13.43条：董事会会议日期的公告须于董事会前至少7个工作天前上载联交所网站（经ESS）及本公司网站",
   "title": "董事会会议日期公告上载ESS（经ESS）及公司网站",
   "steps": "1)制备董事会会议日期公告 2)于董事会前至少7个工作天(8月10日或之前)上载ESS 3)同步公司网站置顶 4)确认回执",
   "pri": "高优",
   "status": "未启动",
   "proj": "董事会",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "board_ann",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "board_ann",
   "eWorkday": false,
   "eDelta": 0,
   "file": "董事会日期公告",
   "note": "T1-10=8/10;13.43"
  },
  {
   "cat": "中期报告",
   "rule": "上市规则13.46(2)+实务：中报框架提前传阅各方协调",
   "title": "中期报告框架传阅+各方协调（审计/印刷商/律师）",
   "steps": "1)8/6前参考联交所最新要求 2)制备中报框架(财务报表/MD&A/CG段) 3)传阅EY/印刷商/律师 4)协调时间节点",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "framework",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "framework",
   "eWorkday": false,
   "eDelta": 0,
   "file": "中报框架",
   "note": "T1-14=8/6开始"
  },
  {
   "cat": "中期报告",
   "rule": "预留至少十个工作天予印刷商进行排版及翻译工作",
   "title": "提交中期报告及业绩公告予印刷商翻译及排版",
   "steps": "1)汇总中报全文(中英文) 2)7月31日或之前交付印刷商 3)确认排版翻译时间表 4)追踪进度",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "print_submit",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "print_submit",
   "eWorkday": false,
   "eDelta": 0,
   "file": "印刷商排期表",
   "note": "T1-20=7/31或之前"
  },
  {
   "cat": "中期报告",
   "rule": "印刷商要求 9/14 18:00前：IR cover预印",
   "title": "IR封面预印交付印刷商（提供总数量）",
   "steps": "1)统计三家公司中报印刷总量 2)9/14 18:00前交付印刷商 3)确认纸张/装订规格 4)取得回执",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "李云巧",
   "agency": "印刷商",
   "sKey": "ir_cover",
   "sWorkday": true,
   "sDelta": -3,
   "eKey": "ir_cover",
   "eWorkday": false,
   "eDelta": 0,
   "file": "IR cover订单",
   "note": "★9/14 18:00硬deadline"
  },
  {
   "cat": "中期报告",
   "rule": "印刷商要求 9/14 23:59前：Sign off E&C Letters(672&1321)",
   "title": "E&C信函定稿（672&1321·律师签署）",
   "steps": "1)律师制备E&C Letters 2)9/14 23:59前sign off 3)2271不需Letter 4)归档",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "林才贺/李云巧",
   "agency": "律师(E&C)",
   "sKey": "ec_letters",
   "sWorkday": true,
   "sDelta": -5,
   "eKey": "ec_letters",
   "eWorkday": false,
   "eDelta": 0,
   "file": "E&C Letters",
   "note": "★9/14 23:59;2271豁免"
  },
  {
   "cat": "中期报告",
   "rule": "印刷商要求 9/17 10:00前：Deliver Letters to registrar",
   "title": "信函交付股份过户处（672&1321·Tricor）",
   "steps": "1)9/17 10:00前将E&C Letters交付Tricor 2)取得签收 3)确认邮寄安排",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "林才贺",
   "agency": "Tricor",
   "sKey": "deliver_letters",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "deliver_letters",
   "eWorkday": false,
   "eDelta": 0,
   "file": "交付回执",
   "note": "★9/17 10:00硬deadline"
  },
  {
   "cat": "中期报告",
   "rule": "印刷商要求 9/17 23:59前：Sign off E&C IR Text(all)",
   "title": "中期报告正文定稿（全部三家公司·律师E&C签署）",
   "steps": "1)律师E&C审阅中报正文 2)★9/17 23:59前sign off 3)中英文双语 4)这是最关键节点",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "李云巧",
   "agency": "律师(E&C)+印刷商",
   "sKey": "text_final",
   "sWorkday": true,
   "sDelta": -7,
   "eKey": "text_final",
   "eWorkday": false,
   "eDelta": 0,
   "file": "中报定稿签字版",
   "note": "★9/17 23:59 全表最关键"
  },
  {
   "cat": "中期报告",
   "rule": "上市规则13.46(2)+印刷实务：中报付印与正文定稿同步",
   "title": "《中期报告》付印（定稿即付印·三家公司）",
   "steps": "1)9/17正文定稿后即交印刷商 2)印刷商同步付印 3)预留5天 4)T2=9/22上传",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "李云巧",
   "agency": "印刷商",
   "sKey": "text_final",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "printing",
   "eWorkday": false,
   "eDelta": 0,
   "file": "中报印刷品",
   "note": "与正文定稿同日9/17"
  },
  {
   "cat": "中期报告",
   "rule": "印刷实务：付印前须与印刷商确认印数",
   "title": "与印刷商确认中期报告印数",
   "steps": "1)统计三家公司中报总印数 2)9月8日或之前与印刷商确认 3)含英文版/存档本数量 4)下达付印指令",
   "pri": "中优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "李云巧",
   "agency": "印刷商",
   "sKey": "confirm_qty",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "confirm_qty",
   "eWorkday": false,
   "eDelta": 0,
   "file": "印数确认单",
   "note": "T1+19=9/8"
  },
  {
   "cat": "中期报告",
   "rule": "上市规则13.46(2)：中期报告须于T0+3个月内上传ESS及公司网站",
   "title": "上传中期报告至HKEX(ESS)+公司网站（收盘后）",
   "steps": "1)通知印刷商9/22收盘后上传 2)分类选'Interim Report' 3)同步公司网站置顶 4)确认回执",
   "pri": "最高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "ess_upload",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "ess_upload",
   "eWorkday": false,
   "eDelta": 0,
   "file": "ESS上传确认",
   "note": "★9/22 after hours;T2锁定"
  },
  {
   "cat": "中期报告",
   "rule": "上市规则14A+实务：持续关连交易须中期清查实际执行vs额度",
   "title": "关连交易中期清查（CCT执行进度·三家公司）",
   "steps": "1)更新关连方清单 2)统计上半年CCT实际金额 3)与年度额度对照 4)超额须立即披露",
   "pri": "高优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "高国萍",
   "agency": "EY安永",
   "sKey": "framework",
   "sWorkday": true,
   "sDelta": -5,
   "eKey": "framework",
   "eWorkday": true,
   "eDelta": 0,
   "file": "CCT中期对照表",
   "note": "中期简查-重点在年度"
  },
  {
   "cat": "中期报告",
   "rule": "（如有）中期股息须于董事会建议派发后寄发",
   "title": "派发股息支票（如有）",
   "steps": "1)董事会授权派发股息 2)确认派息银行户口 3)9月30日或之前寄发股息支票 4)登记派息记录",
   "pri": "中优",
   "status": "未启动",
   "proj": "中期报告",
   "owner": "林才贺",
   "agency": "银行/股份过户处",
   "sKey": "dividend_pay",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "dividend_pay",
   "eWorkday": false,
   "eDelta": 0,
   "file": "股息支票",
   "note": "T2+8=9/30或之前"
  }
 ],
 "annualTasks": [
  {
   "cat": "业绩公告",
   "rule": "附录10 A.3：在年度业绩公告前60天内，董事不得买卖公司证券（除非符合特定条件）",
   "title": "禁止买卖期启动+FF05通知HKEX",
   "steps": "1)计算T1-60天为禁售期首日 2)制备FF05表格列明禁售期起止 3)提交HKEX并抄送全体董事 4)同步通知拥有内幕消息的相关雇员 5)在IM登记册记录",
   "pri": "最高优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "林才贺",
   "agency": "律师(WFW)",
   "sKey": "blackout",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "blackout",
   "eWorkday": false,
   "eDelta": 0,
   "file": "FF005_BLACKOUT_PERIOD_NOTIFICATION",
   "note": "已通知WFW提交FF05"
  },
  {
   "cat": "业绩公告",
   "rule": "上市规则13.49(2)：如知悉财务表现将出现重大变化，须尽快刊发盈利警告或正面盈利预告",
   "title": "监察是否须发出盈警/盈喜公告",
   "steps": "1)取得审计初稿后立即审阅损益表 2)对比去年同期识别重大变化 3)如变化>20%立即起草盈警/盈喜公告 4)经律师+审计复核后刊发",
   "pri": "最高优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "林才贺/李云巧",
   "agency": "律师",
   "sKey": "profitwarn",
   "sWorkday": true,
   "sDelta": -7,
   "eKey": "profitwarn",
   "eWorkday": false,
   "eDelta": 0,
   "file": "盈利警告公告",
   "note": "3月20日已刊发"
  },
  {
   "cat": "业绩公告",
   "rule": "审计实务+13.49：年度业绩须基于经审计财务报表；审计须按HKSA准则执行",
   "title": "审计报告初稿（进场→损益表→底稿→定稿）",
   "steps": "1)T1-90天审计进场 2)T1-70天沟通损益表 3)T1-20天底稿完成 4)T1-17天初稿交秘书起草公告 5)经理→合伙人两级复核",
   "pri": "高优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "汤锦涛/高国萍",
   "agency": "EY安永",
   "sKey": "audit_in",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "audit_draft_done",
   "eWorkday": false,
   "eDelta": 0,
   "file": "审计底稿/审计报告",
   "note": "3月19日已获取安永最新底稿"
  },
  {
   "cat": "业绩公告",
   "rule": "CG守则C.3+审计实务：核数师须向审核委员会提交审核情况说明函件，含关键审计事项/持续经营/调整事项",
   "title": "核数师《审核情况说明函件》+意见类型跟踪",
   "steps": "1)要求EY在T1-6天前交函件 2)核对审计意见类型(��保留/保留/否定/无法表示) 3)若非无保留立即启动13.50A应急公告 4)函件归档备查",
   "pri": "最高优",
   "status": "未启动",
   "proj": "业绩公告",
   "owner": "李云巧/汤锦涛",
   "agency": "EY安永",
   "sKey": "auditor_letter",
   "sWorkday": true,
   "sDelta": -7,
   "eKey": "auditor_letter",
   "eWorkday": false,
   "eDelta": 0,
   "file": "审核情况说明函件",
   "note": "必须在董事会前收到"
  },
  {
   "cat": "业绩公告",
   "rule": "上市规则13.49附录D+HKAS 570：MD&A须包含持续经营假设及不确定因素",
   "title": "管理层讨论及分析(MD&A)+持续经营单独段",
   "steps": "1)基于审计初稿起草MD&A 2)单独一段写持续经营假设(含不确定因素) 3)股息政策执行说明 4)投资物业及主要物业盘点 5)中英文双语",
   "pri": "高优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "汤锦涛/高国萍/李云巧",
   "agency": "内部",
   "sKey": "mda",
   "sWorkday": true,
   "sDelta": -7,
   "eKey": "mda",
   "eWorkday": false,
   "eDelta": 0,
   "file": "业绩公告(中/英)",
   "note": "1321:3月9日已填完一版"
  },
  {
   "cat": "业绩公告",
   "rule": "上市规则13.46(2)+实务：业绩公告与年报数据须一致",
   "title": "业绩公告vs年报数据一致性逐数核对（双签）",
   "steps": "1)建Sign-off Checklist列出所有关键数字(营收/利润/股息/资产) 2)财务负责人逐数核对 3)公司秘书复核 4)双签确认后付印",
   "pri": "高优",
   "status": "未启动",
   "proj": "业绩公告",
   "owner": "李云巧",
   "agency": "内部",
   "sKey": "rh_nrh",
   "sWorkday": true,
   "sDelta": -10,
   "eKey": "rh_nrh",
   "eWorkday": false,
   "eDelta": 0,
   "file": "Sign-off Checklist",
   "note": "T2-10=9/12开始核对"
  },
  {
   "cat": "业绩公告",
   "rule": "内幕消息规定：发行人对内幕消息须备存书面记录",
   "title": "内幕消息登记册(IM Register)更新",
   "steps": "1)禁售期启动通知 2)董事/雇员沟通记录 3)业绩框架传阅记录 4)盈警判断过程 5)统一入IM登记册按月归档",
   "pri": "中优",
   "status": "未启动",
   "proj": "业绩公告",
   "owner": "林才贺",
   "agency": "内部",
   "sKey": "internal_ctrl",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "internal_ctrl",
   "eWorkday": false,
   "eDelta": 0,
   "file": "IM Register",
   "note": "与年度同机制"
  },
  {
   "cat": "业绩公告",
   "rule": "附录10+第10章：董事会为业绩开会前1个月禁回购",
   "title": "回购静默期冲突检查+有关雇员政策通知",
   "steps": "1)确认公司是否有回购授权 2)若有T1前1个月起禁回购 3)同时通知'有关雇员'(高管/财务)禁售 4)检查现有书面政策是否涵盖",
   "pri": "中优",
   "status": "未启动",
   "proj": "业绩公告",
   "owner": "林才贺",
   "agency": "内部",
   "sKey": "audit_in",
   "sWorkday": true,
   "sDelta": 30,
   "eKey": "audit_in",
   "eWorkday": true,
   "eDelta": 60,
   "file": "回购授权文件/雇员政策",
   "note": "无回购授权则跳过"
  },
  {
   "cat": "董事合规",
   "rule": "CG守则+实务：董事须年度确认培训/独立性/任职等",
   "title": "收集董事培训记录+制备确认书",
   "steps": "1)向各董事发函收集年内培训证明 2)汇总培训主题/时数/提供方 3)制备确认书由董事签署 4)律师审阅 5)年报CG段披露",
   "pri": "低优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "internal_ctrl",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "internal_ctrl",
   "eWorkday": true,
   "eDelta": -20,
   "file": "培训确认书PDF",
   "note": "已完成"
  },
  {
   "cat": "董事合规",
   "rule": "CG守则：INED须年度确认独立性",
   "title": "为INED制备独立性年度确认函",
   "steps": "1)向每名INED发独立性确认函模板 2)列明7项独立性因素逐一确认 3)董事签署 4)律师审阅 5)年报CG段披露",
   "pri": "低优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "internal_ctrl",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "internal_ctrl",
   "eWorkday": true,
   "eDelta": -20,
   "file": "INED确认书PDF",
   "note": "已完成"
  },
  {
   "cat": "董事合规",
   "rule": "标准守则：董事须年度确认遵守",
   "title": "董事年度确认遵守标准守则+简历更新",
   "steps": "1)制备标准守则遵守确认书 2)请董事确认年内无违规 3)同步更新董事简历(教育/经历/兼任) 4)双签归档",
   "pri": "低优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "internal_ctrl",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "internal_ctrl",
   "eWorkday": true,
   "eDelta": -20,
   "file": "标准守则确认书/简历",
   "note": "已完成"
  },
  {
   "cat": "董事合规",
   "rule": "CG守则：董事须年度确认其他任职及重大承担",
   "title": "董事其他任职及重大承担确认书",
   "steps": "1)制备确认书模板列明所有外部职位 2)董事填写 3)律师核对与年报披露一致性 4)缺失者催办",
   "pri": "低优",
   "status": "未启动",
   "proj": "业绩公告",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "internal_ctrl",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "internal_ctrl",
   "eWorkday": true,
   "eDelta": -20,
   "file": "任职确认书",
   "note": "催办中"
  },
  {
   "cat": "董事合规",
   "rule": "法律意见：新任/连任董事须签责任确认书",
   "title": "董事责任确认书（含法律意见日期）",
   "steps": "1)制备责任确认书(含董事理解职责的声明) 2)记录取得法律意见的日期 3)新任/连任董事分别签署 4)律师审阅",
   "pri": "高优",
   "status": "未启动",
   "proj": "业绩公告",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "internal_ctrl",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "internal_ctrl",
   "eWorkday": true,
   "eDelta": -20,
   "file": "责任确认书",
   "note": "须法律意见日期"
  },
  {
   "cat": "董事合规",
   "rule": "上市规则3.13A过渡期：INED连续任职≥9年须披露",
   "title": "INED连续任职≥9年声明(3.13A过渡期)",
   "steps": "1)核对每名INED累计任职年限 2)若≥9年制备额外声明 3)CG报告披露过渡安排 4)律师审阅",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -60,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "INED声明",
   "note": "CG段披露"
  },
  {
   "cat": "董事合规",
   "rule": "上市规则：INED兼任HK上市公司≤6家须披露",
   "title": "INED兼任HK上市公司≤6家声明",
   "steps": "1)统计每名INED现任HK上市公司董事席位数 2)若≥6家制备声明 3)CG报告披露 4)提醒INED接任能力",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -60,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "INED兼任统计",
   "note": "CG段披露"
  },
  {
   "cat": "董事合规",
   "rule": "CG守则：须披露董事会技能矩阵",
   "title": "编制并披露董事会技能矩阵",
   "steps": "1)列出每名董事核心技能标签 2)汇总为技能矩阵表 3)说明技能组合如何符合公司策略 4)CG报告披露",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -60,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "技能矩阵表",
   "note": "CG段披露"
  },
  {
   "cat": "董事合规",
   "rule": "提名委员会：年度评估董事贡献",
   "title": "提名委员会年度时间投入与贡献评估结论",
   "steps": "1)收集每名董事年内出席记录 2)提名委会议讨论评估 3)形成评估结论 4)CG报告披露过程及结论",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "林才贺",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -60,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "提名委评估结论",
   "note": "CG段披露"
  },
  {
   "cat": "董事合规",
   "rule": "董事会多元化政策须年度披露进度",
   "title": "董事会多元化政策年度进度披露",
   "steps": "1)审视现有多元化政策 2)统计性别/年龄/技能分布 3)对照目标写进度说明 4)CG报告披露",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -60,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "多元化进度表",
   "note": "CG段披露"
  },
  {
   "cat": "董事合规",
   "rule": "CG守则：董事出席率须披露",
   "title": "董事出席率计算表（董事会/股东会/各委员会）",
   "steps": "1)从会议记录提取每名董事出席 2)计算出席率 3)汇总为表格 4)律师审阅后入年报CG段",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "林才贺/李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "出席率计算表",
   "note": "CG段披露"
  },
  {
   "cat": "董事合规",
   "rule": "CG守则：委员会会议记录须收集",
   "title": "薪酬/提名/审核委员会开会记录收集",
   "steps": "1)收集各委员会年内所有会议记录 2)核对召开次数达标 3)审核委确认含无管理层在场见核数师会议 4)律师审阅",
   "pri": "低优",
   "status": "已完成",
   "proj": "业绩公告",
   "owner": "林才贺",
   "agency": "律师",
   "sKey": "internal_ctrl",
   "sWorkday": true,
   "sDelta": -50,
   "eKey": "internal_ctrl",
   "eWorkday": true,
   "eDelta": -20,
   "file": "委员会会议记录",
   "note": "已完成"
  },
  {
   "cat": "董事会",
   "rule": "公司章程+上市规则13.48：董事会须批准年度业绩公告及年报",
   "title": "董事会议程传送+通告发出(≥14天)",
   "steps": "1)确定董事会日期后计算14天前 2)制备会议通告及议程 3)电子邮件+书面双轨发送全体董事 4)确认收悉",
   "pri": "高优",
   "status": "已完成",
   "proj": "董事会",
   "owner": "林才贺",
   "agency": "内部人力行政",
   "sKey": "internal_ctrl",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "internal_ctrl",
   "eWorkday": false,
   "eDelta": 0,
   "file": "董事会通告/议程",
   "note": "T1-14=董事会通告"
  },
  {
   "cat": "董事会",
   "rule": "CG守则C.3.3：审计师须向审核委员会提交材料",
   "title": "审计师提交审核委员会材料",
   "steps": "1)T1-7天前要求审计师提交审核委专属材料 2)含关键审计事项/持续经营/核数费用 3)安排审核委会议 4)记录决议",
   "pri": "高优",
   "status": "已完成",
   "proj": "董事会",
   "owner": "林才贺",
   "agency": "EY安永",
   "sKey": "ac_material",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "ac_material",
   "eWorkday": false,
   "eDelta": 0,
   "file": "审核委材料",
   "note": "审核委材料"
  },
  {
   "cat": "董事会",
   "rule": "CG守则C.3+风险管理守则：内控报告须提前交审核委",
   "title": "内控部门提交年度内控报告(提前一周)",
   "steps": "1)T1-9天前通知内审部门准备 2)提前一周交审核委审阅 3)收集审核委意见 4)修改后入董事会材料",
   "pri": "高优",
   "status": "已完成",
   "proj": "董事会",
   "owner": "李云巧/林才贺",
   "agency": "内部审计部门",
   "sKey": "internal_ctrl",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "internal_ctrl",
   "eWorkday": false,
   "eDelta": 0,
   "file": "内控报告",
   "note": "内控报告"
  },
  {
   "cat": "董事会",
   "rule": "上市规则13.48：董事会须批准业绩公告/年报/股息",
   "title": "收集及传阅董事会材料+草拟会议纪要",
   "steps": "1)汇编7模块材料 2)T1-2天定稿发送 3)会后草拟会议纪要",
   "pri": "最高优",
   "status": "已完成",
   "proj": "董事会",
   "owner": "林才贺/李云巧",
   "agency": "内部",
   "sKey": "board_mat",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "board_mat",
   "eWorkday": false,
   "eDelta": 0,
   "file": "董事会材料全套",
   "note": "T1-2=董事会材料"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则附录D+ESG指引：须披露气候四支柱+范围1+2",
   "title": "ESG报告(含气候四支柱+范围1+2)",
   "steps": "1)治理段写董事会监督气候职责 2)战略段含气候情景分析 3)风险段列气候相关风险识别流程 4)指标段披范围1+2排放量 5)律师审阅",
   "pri": "高优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "印刷商",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "ESG报告",
   "note": "ESG报告"
  },
  {
   "cat": "年报ESG",
   "rule": "公司治理：主席报告",
   "title": "主席报告",
   "steps": "1)起草主席致辞(业务回顾/展望/致谢) 2)与MD&A口径核对 3)律师审阅 4)主席签署",
   "pri": "中优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "姚峣",
   "agency": "内部",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "主席报告",
   "note": "主席报告"
  },
  {
   "cat": "年报ESG",
   "rule": "CG守则：须披露企业管治报告",
   "title": "企业管治报告(CG)含技能表/多元化/INED声明",
   "steps": "1)汇编技能矩阵+多元化进度+INED声明+出席率+委员会记录 2)律师审阅 3)人力行政确认 4)入年报",
   "pri": "高优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "林才贺",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "CG报告",
   "note": "CG报告"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则：董事及高级管理层履历(C07/C08)",
   "title": "董事及高级管理层履历(C07/C08)",
   "steps": "1)向各董事更新履历 2)加技能标签+兼任家数 3)人力行政确认 4)律师审阅 5)双签",
   "pri": "中优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "董事履历.docx",
   "note": "董事履历"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则：董事会报告",
   "title": "董事会报告",
   "steps": "1)起草业务回顾 2)列主要风险及应对 3)股息建议(如有) 4)资本结构说明 5)律师审阅",
   "pri": "中优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "董事会报告",
   "note": "董事会报告"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则：股份计划5项限额须核对",
   "title": "股份计划5项限额披露核对",
   "steps": "1)核对购股权计划/股份奖励计划 2)授出期权归属期是否合规 3)奖励可发行股数≤上限 4)服务商分项限额 5)可授出数余额",
   "pri": "高优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "股份计划核对表",
   "note": "股份计划"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则：募集资金用途(UOP)须披露结转",
   "title": "募集资金用途(UOP)往期结转明细",
   "steps": "1)列出所有历史募集资金项目 2)结转余额 3)当年实际使用金额 4)差异说明 5)核数师确认",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "高国萍",
   "agency": "EY安永",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "UOP明细表",
   "note": "UOP明细"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则：重大投资>5%总资产须披露",
   "title": "重大投资>5%总资产：持股数量+百分比+风控",
   "steps": "1)列出所有>5%总资产的投资 2)披持股数量(非仅比例) 3)投资组合明细 4)风控机制说明 5)律师审阅",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "汤锦涛",
   "agency": "内部",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "重大投资明细",
   "note": "重大投资"
  },
  {
   "cat": "年报ESG",
   "rule": "公司条例：库存股份拟定用途须声明",
   "title": "库存股份拟定用途声明",
   "steps": "1)核查公司是否有库存股份 2)若有说明拟定用途(如员工奖励) 3)若无声明'本公司无库存股份' 4)律师审阅",
   "pri": "中优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "律师",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "库存股份声明",
   "note": "库存股份"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则13.46：中英文伴送声明+RH/NRH Letter",
   "title": "年报中英文伴送声明+RH/NRH Letter措辞",
   "steps": "1)确认送股东方式(纸质/电子/无纸化) 2)RH Letter(送年报通知)定稿 3)NRH Letter(不送通知)定稿 4)嵌中英文伴送声明 5)印刷前律师签字",
   "pri": "高优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "rh_nrh",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "rh_nrh",
   "eWorkday": false,
   "eDelta": 0,
   "file": "RH/NRH Letter",
   "note": "RH/NRH Letter"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则13.46(1)：年报须T0+4个月内付印上传",
   "title": "《年报》最后定稿+大量付印(预留3个工作日)",
   "steps": "1)T2-3天前全部材料定稿 2)交印刷商 3)预留3个工作日印刷+送过户处 4)T2当日上传ESS 5)同步公司网站",
   "pri": "最高优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "李云巧",
   "agency": "印刷商",
   "sKey": "annual_print",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "annual_print",
   "eWorkday": false,
   "eDelta": 0,
   "file": "年报定稿",
   "note": "年报定稿"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则13.46(1)：年报+ESG须上传ESS及公司网站",
   "title": "上传年报/ESG/RH/NRH Letter至HKEX(ESS)+公司网站",
   "steps": "1)通知印刷商上传 2)年报→Financial Statements 3)ESG→同路径-ESG 4)RH→Circulars-[Other] 5)公司网站同步置顶",
   "pri": "最高优",
   "status": "已完成",
   "proj": "年报ESG",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "ess_a",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "ess_a",
   "eWorkday": false,
   "eDelta": 0,
   "file": "ESS上传确认",
   "note": "ESS上传"
  },
  {
   "cat": "年报ESG",
   "rule": "上市规则14A+实务：持续关连交易须年度清查",
   "title": "关连交易年度清查(CCT额度执行对照)",
   "steps": "1)年末关连方清单更新 2)持续关连交易实际金额统计 3)与年报批准的年度额度对照 4)超额须立即披露 5)律师审阅",
   "pri": "高优",
   "status": "未启动",
   "proj": "年报ESG",
   "owner": "高国萍",
   "agency": "EY安永",
   "sKey": "ess_a",
   "sWorkday": true,
   "sDelta": -70,
   "eKey": "ess_a",
   "eWorkday": true,
   "eDelta": -10,
   "file": "CCT对照表",
   "note": "CCT对照"
  },
  {
   "cat": "AGM",
   "rule": "上市规则13.66(1)：暂停股份过户登记须≥10营业日通知",
   "title": "暂停股份过户登记通知HKEX及过户处(≥10营业日)",
   "steps": "1)计算T3-21天-10营业日≈T3-31天为最迟通知日 2)书面通知HKEX 3)同步通知Tricor 4)确认回执",
   "pri": "最高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺",
   "agency": "Tricor",
   "sKey": "suspend_notice",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "suspend_notice",
   "eWorkday": false,
   "eDelta": 0,
   "file": "暂停过户通知函",
   "note": "暂停过户通知"
  },
  {
   "cat": "AGM",
   "rule": "公司章程第47条：暂停登记≤4个工作日含AGM当日",
   "title": "暂停股份过户登记办理(≤4个工作日,含AGM当日)",
   "steps": "1)安排暂停4个工作天 2)含AGM召开日在内 3)全年累计不超30天 4)通知股东暂停安排",
   "pri": "高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺",
   "agency": "Tricor",
   "sKey": "suspend_start",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "suspend_start",
   "eWorkday": false,
   "eDelta": 0,
   "file": "暂停安排表",
   "note": "暂停安排"
  },
  {
   "cat": "AGM",
   "rule": "上市规则13.39(4)：AGM后当晚23:00前上传投票结果",
   "title": "AGM投票结果公告模板+当晚23:00前ESS上传",
   "steps": "1)提前备投票结果公告模板 2)含退任董事重选票数/INED比例/法定人数 3)AGM结束后立即填数 4)当晚23:00前ESS上传",
   "pri": "最高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺",
   "agency": "印刷商/Tricor",
   "sKey": "vote_result",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "vote_result",
   "eWorkday": false,
   "eDelta": 0,
   "file": "投票结果公告模板",
   "note": "投票结果"
  },
  {
   "cat": "AGM",
   "rule": "上市规则13.39+ESS：IF001报备最终AGM时间",
   "title": "IF001表格提交HKEX报备最终AGM时间",
   "steps": "1)AGM日期锁定后制备IF001 2)经公司秘书签字 3)上传ESS 4)确认HKEX收悉",
   "pri": "高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺",
   "agency": "内部",
   "sKey": "if001",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "if001",
   "eWorkday": false,
   "eDelta": 0,
   "file": "IF001表格",
   "note": "IF001"
  },
  {
   "cat": "AGM",
   "rule": "公司条例622：AGM须于T0+6个月内召开",
   "title": "AGM最迟召开日备忘(T0+6个月)",
   "steps": "1)在日历标注T0+6个月为AGM最迟日 2)当前T3须≤此日 3)留4天余量防延期",
   "pri": "中优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺",
   "agency": "内部",
   "sKey": "T0",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "T0",
   "eWorkday": false,
   "eDelta": 183,
   "file": "AGM备忘",
   "note": "T0+6个月"
  },
  {
   "cat": "AGM",
   "rule": "公司章程第65条：AGM通告须含退任董事重选说明",
   "title": "AGM通告付印(退任董事重选说明+委任表截止)",
   "steps": "1)制备AGM通告含全部决议案 2)退任董事重选说明 3)RH/NRH Letter随附 4)印刷商付印",
   "pri": "高优",
   "status": "已完成",
   "proj": "AGM",
   "owner": "林才贺/李云巧",
   "agency": "印刷商",
   "sKey": "vote_result",
   "sWorkday": true,
   "sDelta": -18,
   "eKey": "T4",
   "eWorkday": false,
   "eDelta": 0,
   "file": "AGM通告/代表委任表",
   "note": "AGM通告"
  },
  {
   "cat": "AGM",
   "rule": "公司章程：代表委任表须AGM前48小时送达",
   "title": "收集代表委任表之最后限期(AGM前48小时)",
   "steps": "1)制备代表委任表模板 2)通知主要股东 3)AGM前48小时为最后收件截止 4)统计委任数确保法定人数",
   "pri": "高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺/李云巧",
   "agency": "Tricor",
   "sKey": "T4",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "T4",
   "eWorkday": false,
   "eDelta": 0,
   "file": "代表委任表",
   "note": "代表委任表"
  },
  {
   "cat": "AGM",
   "rule": "上市规则13.66(2)：AGM记录须会后呈交",
   "title": "AGM记录日，向股份过户处索取最新股东名单",
   "steps": "1)AGM当日(T3)为记录日 2)向Tricor索取截至当日的最新股东名册 3)核对投票权 4)归档",
   "pri": "高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺",
   "agency": "Tricor",
   "sKey": "vote_result",
   "sWorkday": true,
   "sDelta": -5,
   "eKey": "vote_result",
   "eWorkday": false,
   "eDelta": 0,
   "file": "最新股东名册",
   "note": "最新股东名册"
  },
  {
   "cat": "AGM",
   "rule": "上市规则13.66(2)：AGM后15天内呈交会议记录",
   "title": "AGM会议记录定稿+呈交HKEX(15天内)",
   "steps": "1)AGM后立即起草会议纪要 2)含出席名单/法定人数/INED比例/决议结果 3)核证本盖章 4)T3+15天内呈交HKEX",
   "pri": "高优",
   "status": "未启动",
   "proj": "AGM",
   "owner": "林才贺/李云巧",
   "agency": "内部",
   "sKey": "agm_record",
   "sWorkday": false,
   "sDelta": 0,
   "eKey": "agm_record",
   "eWorkday": false,
   "eDelta": 0,
   "file": "AGM会议纪要核证本",
   "note": "AGM会议纪要"
  },
  {
   "cat": "AGM",
   "rule": "实务：AGM需场地+独立点票员",
   "title": "预订场地+聘请点票员(Tricor)+邀请嘉宾",
   "steps": "1)预订AGM场地(酒店/办公室) 2)聘请Tricor为独立点票员 3)邀请核数师/委员会主席/嘉宾 4)确认董事出席及代表人数",
   "pri": "中优",
   "status": "部分完成",
   "proj": "AGM",
   "owner": "李云巧",
   "agency": "Tricor",
   "sKey": "vote_result",
   "sWorkday": true,
   "sDelta": -60,
   "eKey": "vote_result",
   "eWorkday": true,
   "eDelta": -14,
   "file": "场地/点票员合同",
   "note": "场地/点票员"
  }
 ],
 "defaults": {
  "interim": {
   "code": "1321",
   "name": "中国新城市",
   "name_en": "China New City Group Limited",
   "T0": "2026-06-30",
   "T1": "2026-08-20",
   "T2": "2026-09-22",
   "blackout_days": 30,
   "earliest_board": "2026-08-20",
   "ess_date": "2026-09-22",
   "related": [
    "2271 众安智慧生活",
    "0672 第三家关联公司"
   ],
   "fiscal_year": "自然年（1-12月）",
   "holidays": []
  },
  "annual": {
   "code": "1321",
   "name": "中国新城市",
   "name_en": "China New City Group Limited",
   "T0": "2026-12-31",
   "T1": "2027-03-26",
   "T2": "2027-04-23",
   "T3": "2027-06-04",
   "T4": "2027-05-14",
   "blackout_days": 60,
   "earliest_board": "2027-03-26",
   "ess_date": "2027-04-23",
   "related": [],
   "fiscal_year": "自然年（1-12月）",
   "holidays": []
  }
 }
}